#!/bin/bash
#  Copyright (c) 2020-2021 Matus Chochlik
#  clang-tidy cache wrapper script
#
if [[ ${CTCACHE_SKIP:-0} -ne 0 ]]
then exit 0
fi

CTCACHE_CLANG_TIDY="${CTCACHE_CLANG_TIDY:-/usr/bin/clang-tidy}"

if [[ ${CTCACHE_DISABLE:-0} -ne 0 ]]
then "${CTCACHE_CLANG_TIDY}" "${@}"
else "$(dirname $(realpath ${0}))/clang-tidy-cache" "${CTCACHE_CLANG_TIDY}" "${@}"
fi
