#!/usr/bin/env python3
# coding: UTF-8
# Copyright (c) 2019-2021 Matus Chochlik
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
#  http://www.boost.org/LICENSE_1_0.txt

import os
import re
import sys
import errno
import getpass
import logging
import hashlib
import requests
import tempfile
import subprocess

# ------------------------------------------------------------------------------


class ClangTidyCacheOpts(object):
    # --------------------------------------------------------------------------
    def __init__(self, log, args):
        self._original_args = args
        self._clang_tidy_args = []
        self._compiler_args = []
        self._cache_dir = ""

        self._strip_list = os.getenv("CTCACHE_STRIP", "").split(':')

        for i in range(len(args)):
            if args[i] == "--":
                self._clang_tidy_args = args[:i]
                self._compiler_args = args[i+1:]

        self._compiler_args.insert(1, "-D__clang_analyzer__=1")

        if self._compiler_args:
            for i in range(1, len(self._compiler_args)):
                if self._compiler_args[i-1] in ["-o", "--output"]:
                    self._compiler_args[i] = "-"
                if self._compiler_args[i-1] in ["-c"]:
                    self._compiler_args[i-1] = "-E"

    # --------------------------------------------------------------------------
    def should_print_dir(self):
        try:
            return self._original_args[0] == "--cache-dir"
        except IndexError:
            return False
    # --------------------------------------------------------------------------

    def should_print_stats(self):
        try:
            return self._original_args[0] == "--show-stats"
        except IndexError:
            return False
    # --------------------------------------------------------------------------

    def should_remove_dir(self):
        try:
            return self._original_args[0] == "--clean"
        except IndexError:
            return False
    # --------------------------------------------------------------------------

    def original_args(self):
        return self._original_args
    # --------------------------------------------------------------------------

    def clang_tidy_args(self):
        return self._clang_tidy_args
    # --------------------------------------------------------------------------

    def compiler_args(self):
        return self._compiler_args
    # --------------------------------------------------------------------------

    @property
    def cache_dir(self):
        if self._cache_dir:
            return self._cache_dir

        try:
            user = getpass.getuser()
        except KeyError:
            user = "unknown"
        self._cache_dir = os.getenv(
            "CTCACHE_DIR",
            os.path.join(
                tempfile.tempdir if tempfile.tempdir else "/tmp", "ctcache-" + user
            ),
        )
        return self._cache_dir

    # --------------------------------------------------------------------------
    def adjust_chunk(self, x):
        x = x.strip()
        r = str().encode("utf8")
        if not x.startswith("# "):
            for w in x.split():
                w = w.strip('"')
                if os.path.exists(w):
                    w = os.path.realpath(w)
                for item in self._strip_list:
                    w = w.replace(item, '')
                w.strip()
                if w:
                    r += w.encode("utf8")
        return r

    # --------------------------------------------------------------------------
    def has_s3(self):
        return "CTCACHE_S3_BUCKET" in os.environ

    # --------------------------------------------------------------------------
    def s3_bucket(self):
        return os.getenv("CTCACHE_S3_BUCKET")

    # --------------------------------------------------------------------------
    def s3_bucket_folder(self):
        return os.getenv("CTCACHE_S3_FOLDER", 'clang-tidy-cache')

    # --------------------------------------------------------------------------
    def has_host(self):
        return os.getenv("CTCACHE_HOST") is not None

    # --------------------------------------------------------------------------
    def rest_host(self):
        return os.getenv("CTCACHE_HOST", "localhost")

    # --------------------------------------------------------------------------
    def rest_port(self):
        return int(os.getenv("CTCACHE_PORT", 5000))

    # --------------------------------------------------------------------------
    def dump_enabled(self):
        return "CTCACHE_DUMP" in os.environ

# ------------------------------------------------------------------------------


class ClangTidyCacheHash(object):
    # --------------------------------------------------------------------------
    def _opendump(self, opts):
        return open(os.path.join(tempfile.gettempdir(), "ctcache.dump"), "ab")

    # --------------------------------------------------------------------------
    def __init__(self, opts):
        self._hash = hashlib.sha1()
        self._dump = self._opendump(opts) if opts.dump_enabled() else None
        assert self._dump or not opts.dump_enabled()

    # --------------------------------------------------------------------------
    def __del__(self):
        if self._dump:
            self._dump.close()

    # --------------------------------------------------------------------------
    def update(self, content):
        if content:
            self._hash.update(content)
            if self._dump:
                self._dump.write(content)

    # --------------------------------------------------------------------------
    def hexdigest(self):
        return self._hash.hexdigest()


class ClangTidyLocalCache(object):
    def __init__(self, log, opts):
        self._log = log
        self._opts = opts

    def is_cached(self, opts, digest):
        path = self._make_path(digest)
        if os.path.isfile(path):
            os.utime(path, None)
            return True
        return False

    def store_in_cache(self, opts, digest):
        p = self._make_path(digest)
        self._mkdir_p(os.path.dirname(p))
        open(p, "w").close()

    def _mkdir_p(self, path):
        try:
            os.makedirs(path)
        except OSError as os_error:
            if os_error.errno == errno.EEXIST and os.path.isdir(path):
                pass
            else:
                raise

    def _make_path(self, digest):
        return os.path.join(self._opts.cache_dir, digest[:2], digest[2:])


class ClangTidyServerCache(object):
    def __init__(self, log, opts):
        self._log = log
        self._opts = opts

    def is_cached(self, digest):
        try:
            query = requests.get(self._make_query_url(digest), timeout=3)
            if query.status_code == 200:
                if query.json() == True:
                    return True
                else:
                    self._log.error("is_cached: Can't connect to server {0}, error {1}".format(
                        self._opts.rest_host(), query.status_code))
        except:
            pass
        return False

    def store_in_cache(self, digest):
        try:
            query = requests.get(self._make_store_url(digest), timeout=3)
            if query.status_code == 200:
                return
            else:
                self._log.error("store_in_cache: Can't store data in server {0}, error {1}".format(
                    self._opts.rest_host(), query.status_code))
        except:
            pass

    def query_stats(self):
        try:
            query = requests.get(self._make_stats_url(), timeout=3)
            if query.status_code == 200:
                return query.json()
            else:
                self._log.error("query_stats: Can't connect to server {0}, error {1}".format(
                    self._opts.rest_host(), query.status_code))
        except:
            pass
        return {}

    def _make_query_url(self, digest):
        return "http://%(host)s:%(port)d/is_cached/%(digest)s" % {
            "host": self._opts.rest_host(),
            "port": self._opts.rest_port(),
            "digest": digest
        }

    def make_store_url(self, digest):
        return "http://%(host)s:%(port)d/cache/%(digest)s" % {
            "host": self._opts.rest_host(),
            "port": self._opts.rest_port(),
            "digest": digest
        }

    def make_stats_url(self):
        return "http://%(host)s:%(port)d/stats" % {
            "host": self._opts.rest_host(),
            "port": self._opts.rest_port()
        }


class ClangTidyLocalCache(object):
    def __init__(self, log, opts):
        self._log = log
        self._opts = opts

    def is_cached(self, digest):
        path = self._make_path(digest)
        if os.path.isfile(path):
            os.utime(path, None)
            return True

        return False

    def store_in_cache(self, digest):
        p = self._make_path(digest)
        self._mkdir_p(os.path.dirname(p))
        open(p, "w").close()

    def _mkdir_p(self, path):
        try:
            os.makedirs(path)
        except OSError as os_error:
            if os_error.errno == errno.EEXIST and os.path.isdir(path):
                pass
            else:
                raise

    def _make_path(self, digest):
        return os.path.join(self._opts.cache_dir, digest[:2], digest[2:])


class ClangTidyS3Cache(object):
    def __init__(self, log, opts):
        from boto3 import client
        from botocore.exceptions import ClientError
        self._ClientError = ClientError
        self._log = log
        self._opts = opts
        self._client = client('s3')
        self._bucket = opts.s3_bucket()
        self._bucket_folder = opts.s3_bucket_folder()

    def is_cached(self, digest):
        try:
            path = self._make_path(digest)
            self._client.get_object(Bucket=self._bucket, Key=path)
        except self._ClientError as e:
            if e.response['Error']['Code'] == "NoSuchKey":
                return False
            else:
                self._log.error(
                    "Error calling S3:get_object {}".format(str(e)))
                raise

        return True

    def store_in_cache(self, digest):
        try:
            path = self._make_path(digest)
            self._client.put_object(Bucket=self._bucket, Key=path, Body=digest)
        except self._ClientError as e:
            self._log.error("Error calling S3:put_object {}".format(str(e)))
            raise

    def _make_path(self, digest):
        return os.path.join(
            self._bucket_folder,
            digest[:2],
            digest[2:]
        )


class ClangTidyCache(object):
    def __init__(self, log, opts):
        self._log = log
        self._opts = opts
        self._local_cache = ClangTidyLocalCache(log, opts)
        self._server_cache = ClangTidyServerCache(
            log, opts) if opts.has_host() else None
        self._s3_cache = ClangTidyS3Cache(
            log, opts) if opts.has_s3() else None

    def is_cached(self, digest):
        if self._local_cache.is_cached(digest):
            return True

        if self._server_cache != None and self._server_cache.is_cached(digest):
            return True

        if self._s3_cache != None and self._s3_cache.is_cached(digest):
            return True

        return False

    def store_in_cache(self, digest):
        self._local_cache.store_in_cache(digest)

        if self._server_cache != None:
            self._server_cache.store_in_cache(digest)

        if self._s3_cache != None:
            self._s3_cache.store_in_cache(digest)

    def query_stats(self):
        if self._server_cache is not None:
            return self._server_cache.query_stats()

        return {}


# ------------------------------------------------------------------------------
source_file_change_re = re.compile(r'#\s+\d+\s+"([^"]+)".*')


def source_file_changed(cpp_line):
    found = source_file_change_re.match(cpp_line)
    if found:
        found_path = found.group(1)
        if os.path.isfile(found_path):
            return os.path.realpath(os.path.dirname(found_path))

# ------------------------------------------------------------------------------


def find_ct_config(search_path):
    while search_path and search_path != "/":
        search_path = os.path.dirname(search_path)
        ct_config = os.path.join(search_path, '.clang-tidy')
        if os.path.isfile(ct_config):
            return ct_config

# ------------------------------------------------------------------------------


def hash_inputs(opts):
    co_args = opts.compiler_args()
    ct_args = opts.clang_tidy_args()
    if not co_args and not ct_args:
        return None

    result = ClangTidyCacheHash(opts)

    proc = subprocess.Popen(
        co_args,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE
    )
    stdout, stderr = proc.communicate()
    if stderr:
        return None

    src_to_ct_config = dict()
    ct_config_paths = set()

    for line in stdout.splitlines():
        line = line.decode("utf8")
        search_path = source_file_changed(line)
        if search_path:
            try:
                ct_config_path = src_to_ct_config[search_path]
            except KeyError:
                ct_config_path = find_ct_config(search_path)
                src_to_ct_config[search_path] = ct_config_path

            if ct_config_path:
                ct_config_paths.add(ct_config_path)

        chunk = opts.adjust_chunk(line)
        result.update(chunk)

    for ct_config_path in sorted(ct_config_paths):
        with open(ct_config_path, "rt") as ct_config:
            for line in ct_config.readlines():
                chunk = opts.adjust_chunk(line)
                result.update(chunk)

    for chunk in sorted(set([opts.adjust_chunk(arg) for arg in co_args[1:]])):
        result.update(chunk)
    for chunk in sorted(set([opts.adjust_chunk(arg) for arg in ct_args[1:]])):
        result.update(chunk)

    return result.hexdigest()
# ------------------------------------------------------------------------------


def print_stats(opts):
    def _format_bytes(s):
        if s < 10000:
            return "%d B" % (s)
        if s < 10000000:
            return "%d kB" % (s / 1000)
        return "%d MB" % (s / 1000000)

    def _format_time(s):
        if s < 60:
            return "%d seconds" % (s)
        if s < 3600:
            return "%d minutes %d seconds" % (s / 60, s % 60)
        if s < 86400:
            return "%d hours %d minutes" % (s / 3600, (s / 60) % 60)
        if s < 604800:
            return "%d days %d hours" % (s / 86400, (s / 3600) % 24)
        if int(s / 86400) % 7 == 0:
            return "%d weeks" % (s / 604800)
        return "%d weeks %d days" % (s / 604800, (s / 86400) % 7)

    stats = query_stats(opts)
    entries = [
        ("Server host", lambda o, s: o.rest_host()),
        ("Server port", lambda o, s: "%d" % o.rest_port()),
        ("Long-term hit rate", lambda o, s: "%.1f %%" %
         (s["total_hit_rate"] * 100.0)),
        ("Hit rate", lambda o, s: "%.1f %%" % (s["hit_rate"] * 100.0)),
        ("Hit count", lambda o, s: "%d" % s["hit_count"]),
        ("Miss count", lambda o, s: "%d" % s["miss_count"]),
        ("Miss rate", lambda o, s: "%.1f %%" % (s["miss_rate"] * 100.0)),
        ("Max hash age", lambda o, s: "%d days" %
         max(int(k) for k in s["age_days_histogram"])),
        ("Max hash hits", lambda o, s: "%d" % max(int(k)
         for k in s["hit_count_histogram"])),
        ("Cache size", lambda o, s: _format_bytes(s["saved_size_bytes"])),
        ("Cached hashes", lambda o, s: "%d" % s["cached_count"]),
        ("Cleaned hashes", lambda o, s: "%d" % s["cleaned_count"]),
        ("Cleaned ago", lambda o, s: _format_time(s["cleaned_seconds_ago"])),
        ("Saved ago", lambda o, s: _format_time(s["saved_seconds_ago"])),
        ("Uptime", lambda o, s: _format_time(s["uptime_seconds"]))
    ]

    max_len = max(len(e[0]) for e in entries)
    for label, fmtfunc in entries:
        padding = " " * (max_len-len(label))
        try:
            print(label+":", padding, fmtfunc(opts, stats))
        except:
            print(label+":", padding, "N/A")
# ------------------------------------------------------------------------------


def run_clang_tidy_cached(log, opts):
    cache = ClangTidyCache(log, opts)
    digest = None
    try:
        digest = hash_inputs(opts)
        if digest and cache.is_cached(digest):
            return 0
    except Exception as error:
        log.error(str(error))

    result = subprocess.call(opts.original_args())

    if result == 0 and digest:
        try:
            cache.store_in_cache(digest)
        except Exception as error:
            log.error(str(error))

    return result
# ------------------------------------------------------------------------------


def main():
    log = logging.getLogger(os.path.basename(__file__))
    log.setLevel(logging.WARNING)
    try:
        opts = ClangTidyCacheOpts(log, sys.argv[1:])
        if opts.should_print_dir():
            print(opts.cache_dir)
        elif opts.should_remove_dir():
            import shutil

            shutil.rmtree(opts.cache_dir)
        elif opts.should_print_stats():
            print_stats(opts)
        else:
            return run_clang_tidy_cached(log, opts)
        return 0
    except Exception as error:
        log.error(str(error))
        return 1


# ------------------------------------------------------------------------------
if __name__ == "__main__":
    sys.exit(main())
