#!/bin/bash
#  Copyright (c) 2020-2024 Matus Chochlik
#  clang-tidy cache wrapper script
#
if [[ ${CTCACHE_SKIP:-0} -ne 0 ]]
then exit 0
fi

for dir in "/etc/ctcache" "${HOME}/.config/ctcache"
do
	if [[ -d "${dir}" ]]
	then
		for cfg in "${dir}"/*.conf
		do
			if [[ -f "${cfg}" ]]
			then source "${cfg}"
			fi
		done
	fi
done

CTCACHE_CLANG_TIDY="${CTCACHE_CLANG_TIDY:-/usr/bin/clang-tidy}"

python="/usr/bin/env python3"

if [[ ${CTCACHE_DISABLE:-0} -ne 0 ]]
then "${CTCACHE_CLANG_TIDY}" "${CTCACHE_CLANG_TIDY_OPTS[@]}" "${@}"
else $python "$(dirname $(realpath ${0}))/src/ctcache/clang_tidy_cache.py" "${CTCACHE_CLANG_TIDY}" "${CTCACHE_CLANG_TIDY_OPTS[@]}" "${@}"
fi
