#!/bin/bash
# Copyright (c) 2021 Matus Chochlik
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
#  http://www.boost.org/LICENSE_1_0.txt
mkdir -p ~/.local/bin
cp -u "$(dirname ${0})/src/ctcache/clang-tidy" ~/.local/bin
cp -u "$(dirname ${0})/src/ctcache/clang-tidy-cache" ~/.local/bin
