#!/bin/bash
# Copyright (c) 2021 Matus Chochlik
# Distributed under the Boost Software License, Version 1.0.
# See accompanying file LICENSE_1_0.txt or copy at
#  http://www.boost.org/LICENSE_1_0.txt
mkdir -p ~/.local/bin
cp -u "$(dirname ${0})/src/ctcache/clang_tidy_cache_server.py" ~/.local/bin/clang-tidy-cache-server
mkdir -p ~/.local/share/ctcache
cp -r -u "$(dirname ${0})/static" ~/.local/share/ctcache
mkdir -p ~/.config/ctcache
cp -u "$(dirname ${0})/config/ctcache/systemd_env" ~/.config/ctcache
mkdir -p ~/.config/systemd/user
cp -r -u "$(dirname ${0})/systemd/ctcache.service" ~/.config/systemd/user
